### ISSUE TITLE
URL设置错了

### ISSUE THREAD

**Issue by CodeCRH** [YGlacier/YGlacierBlog#1]
_config.yml 里URL错了
所以网址变成了https://yglacier.github.io/YGlacierBlog.github.io/index.html
因此读不到CSS

可看index.html源码中有
<meta property="og:url" content="https://yglacier.github.io/YGlacierBlog.github.io/index.html">

**Comment by YGlacier** [comment]
谢谢大哥，我好了
其实是把root设置错了……
